version: '3.1'
services:
  mysqldb:
    image: mysql:latest
    container_name: employee
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: employee
      MYSQL_USER: rootpass
      MYSQL_PASSWORD: rootpass